name: Generate snake animation

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate Snake SVGs (dark and light)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Generate snake (dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: dfigueroaw
          outputs: dist/snake-dark.svg
          palette: github-dark

      - name: Generate snake (light)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: dfigueroaw
          outputs: dist/snake-light.svg
          palette: github-light

      - name: Verify snake-dark.svg exists
        run: test -f dist/snake-dark.svg && echo "Dark SVG generated!" || (echo "Dark SVG not found!" && exit 1)

      - name: Verify snake-light.svg exists
        run: test -f dist/snake-light.svg && echo "Light SVG generated!" || (echo "Light SVG not found!" && exit 1)

      - name: Push snake SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update snake-dark.svg and snake-light.svg"
          user_name: "DiegoBot"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
